### ISSUE TITLE
Response: 400, ERROR_GLPI_ADD You don't have permission to perform this action

### ISSUE THREAD

**Issue by StefanSa** [wandrey66/Zabbix-WebHook-GLPI#1]
Hi @wandrey66
thank you for your work with this WebHook.
i always get the error message from glpi, that the user does not have the authorization to create the ticket via api.
`Response: 400, ERROR_GLPI_ADD You don't have permission to perform this action`
The user has super-admin rights and the correct `user-id` is transmitted, at least i think that the `user-id` is identical to the `ID` in the user db table of the database.
Do you have an idea why this user cannot create a ticket via api?

thanks for any help here.

**Comment by wandrey66** [comment]
Hi StefanSa, you need to have the app_token and the user and password
![imagen](https://user-images.githubusercontent.com/39711987/112194903-faab8280-8bce-11eb-8910-e56369061609.png)
![imagen](https://user-images.githubusercontent.com/39711987/112195018-16168d80-8bcf-11eb-802e-6b35f572e52e.png)
Check your parameters.

**Comment by StefanSa** [comment]
Hola,

The api client with app token works, which user do i have to take or create and which authorization does this have to have ?

muchas gracias

**Comment by wandrey66** [comment]
Hi StefanSa, we suggest a dedicated user, without relevant privileges, particularly try not to use admin users.
Greetings.

**Comment by wandrey66** [comment]
EOT
