### ISSUE TITLE
First test  v.2

### ISSUE THREAD

**Issue by edsontadeuas** [wandrey66/Zabbix-WebHook-GLPI#2]
I create a new media type with this new version, but im getting this error when try to do a media test using the same configuration that is working on version 1:

00:00:00.613 [Depuração] [GLPI Webhook] login failed: ["ERROR_RESOURCE_NOT_FOUND_NOR_COMMONDBTM","resource not found or isn´t an CommonDBTM instance; Se documentation in http://10.x.x.x/apirest.php/#ERROR_RESOURCE_NOT_FOUND_NOR_COMMONDBTM"]
00:00:00.613 [Depuração] [GLPI Webhook] login failed: Response: 400
00:00:00.613 [Depuração] [GLPI Webhook] notification failed: Login failed: Response: 400.

**Comment by wandrey66** [comment]
Hi edsontadeuas, that look like a login error, not a webhook problem, please check your glpi install and parameters. I've put a picture of my test configuration. 
![imagen](https://user-images.githubusercontent.com/39711987/120381752-75d49780-c2e8-11eb-8c80-552bd354830e.png)

**Comment by edsontadeuas** [comment]
It´s working fine now! Thanks Wandrey!

![image](https://user-images.githubusercontent.com/41075289/120493806-a58baa00-c391-11eb-80d7-c88e454ca534.png)

**Comment by wandrey66** [comment]
Fine, thanks for the feedback, I will close the is..
