### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by laboiteajb** [wandrey66/Zabbix-WebHook-GLPI#3]
Hello,

thank you for your work

I have a problem with your script

GLPI 9.5.5
zabbix 5..4.4

ticket creation does not work

Not against when I remove the argument "{EVENT.TAGS.zbx_glpi_ticket}" the ticket is created

**Comment by laboiteajb** [comment]
00:00:00.359 [Debug] [GLPI Webhook] Login OK session_token: q13bs4m98jqtlh1cvl07lfncig
00:00:00.468 [Debug] [GLPI Webhook] UpdateTicket response: ["ERROR_GLPI_ADD",""]
00:00:00.468 [Debug] [GLPI Webhook] OK ticket: undefined
00:00:00.581 [Debug] [GLPI Webhook] KillSession response: null

**Comment by wandrey66** [comment]
HI laboiteajb, thanks for your report, in the next few days I will have some time and check it with version that you mention.

**Comment by laboiteajb** [comment]
thank you for your work

Can you confirm for me: in "to" I have to put the user ID and not the username?
does this work with an AD account?

When I do the test I think the ticket ID is not retrieved

If I set the variable {EVENT.TAGS.zbx_glpi_ticket} to empty, only the closing incidents are created (I did not test the incidents in update)

**Comment by wandrey66** [comment]
> thank you for your work
> 
> Can you confirm for me: in "to" I have to put the user ID and not the username?
RS: Hi, yes into the field "to" is the id (not name) of the user into glpi.
> does this work with an AD account?
RS: I do not test under AD auth, zabbix, or glpi, but first I think that you will not have a trouble with it.
> 
> When I do the test I think the ticket ID is not retrieved
> 
> If I set the variable {EVENT.TAGS.zbx_glpi_ticket} to empty, only the closing incidents are created (I did not test the incidents in update)

Hi, yes into the field "to" is the id (not name) of the user into glpi.

**Comment by wandrey66** [comment]
> 00:00:00.359 [Debug] [GLPI Webhook] Login OK session_token: q13bs4m98jqtlh1cvl07lfncig 00:00:00.468 [Debug] [GLPI Webhook] UpdateTicket response: ["ERROR_GLPI_ADD",""] 00:00:00.468 [Debug] [GLPI Webhook] OK ticket: undefined 00:00:00.581 [Debug] [GLPI Webhook] KillSession response: null

Hi laboiteajb, I'm testing into GLPI 9.5.3 and all work fine, pay attention on test with that values "Event_Value" for the test can't be "macros", for the test set the next values:
Event_Value:1
Event_Update_Status:0

![imagen](https://user-images.githubusercontent.com/39711987/166395251-63ada891-0421-4203-a4a2-d2463affb0cf.png)
![imagen](https://user-images.githubusercontent.com/39711987/166395295-b2f2aa94-1bfa-484b-bd9b-95601382fc10.png)
